/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSwimmerRouteImport } from './routes/app.swimmer'
import { Route as AppDirectorRouteImport } from './routes/app.director'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppSwimmerIndexRouteImport } from './routes/app.swimmer.index'
import { Route as AppDirectorIndexRouteImport } from './routes/app.director.index'
import { Route as AppCoachIndexRouteImport } from './routes/app.coach.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppSwimmerProfileRouteImport } from './routes/app.swimmer.profile'
import { Route as AppSwimmerHistoryRouteImport } from './routes/app.swimmer.history'
import { Route as AppDirectorReportsRouteImport } from './routes/app.director.reports'
import { Route as AppDirectorInvitationsRouteImport } from './routes/app.director.invitations'
import { Route as AppDirectorGroupsRouteImport } from './routes/app.director.groups'
import { Route as AppCoachWellnessRouteImport } from './routes/app.coach.wellness'
import { Route as AppCoachSwimmersRouteImport } from './routes/app.coach.swimmers'
import { Route as AppCoachInvitationsRouteImport } from './routes/app.coach.invitations'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminRegisterTrainerRouteImport } from './routes/app.admin.register-trainer'
import { Route as AppAdminPreviewRouteImport } from './routes/app.admin.preview'
import { Route as AppAdminPendingRouteImport } from './routes/app.admin.pending'
import { Route as AppAdminInvitationsRouteImport } from './routes/app.admin.invitations'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSwimmerRoute = AppSwimmerRouteImport.update({
  id: '/app/swimmer',
  path: '/app/swimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDirectorRoute = AppDirectorRouteImport.update({
  id: '/app/director',
  path: '/app/director',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/app/coach',
  path: '/app/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSwimmerIndexRoute = AppSwimmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSwimmerRoute,
} as any)
const AppDirectorIndexRoute = AppDirectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDirectorRoute,
} as any)
const AppCoachIndexRoute = AppCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoachRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSwimmerProfileRoute = AppSwimmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSwimmerRoute,
} as any)
const AppSwimmerHistoryRoute = AppSwimmerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppSwimmerRoute,
} as any)
const AppDirectorReportsRoute = AppDirectorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppDirectorRoute,
} as any)
const AppDirectorInvitationsRoute = AppDirectorInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppDirectorRoute,
} as any)
const AppDirectorGroupsRoute = AppDirectorGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppDirectorRoute,
} as any)
const AppCoachWellnessRoute = AppCoachWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AppCoachRoute,
} as any)
const AppCoachSwimmersRoute = AppCoachSwimmersRouteImport.update({
  id: '/swimmers',
  path: '/swimmers',
  getParentRoute: () => AppCoachRoute,
} as any)
const AppCoachInvitationsRoute = AppCoachInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppCoachRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRegisterTrainerRoute = AppAdminRegisterTrainerRouteImport.update({
  id: '/register-trainer',
  path: '/register-trainer',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPreviewRoute = AppAdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPendingRoute = AppAdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInvitationsRoute = AppAdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/coach': typeof AppCoachRouteWithChildren
  '/app/director': typeof AppDirectorRouteWithChildren
  '/app/swimmer': typeof AppSwimmerRouteWithChildren
  '/app/admin/invitations': typeof AppAdminInvitationsRoute
  '/app/admin/pending': typeof AppAdminPendingRoute
  '/app/admin/preview': typeof AppAdminPreviewRoute
  '/app/admin/register-trainer': typeof AppAdminRegisterTrainerRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/coach/invitations': typeof AppCoachInvitationsRoute
  '/app/coach/swimmers': typeof AppCoachSwimmersRoute
  '/app/coach/wellness': typeof AppCoachWellnessRoute
  '/app/director/groups': typeof AppDirectorGroupsRoute
  '/app/director/invitations': typeof AppDirectorInvitationsRoute
  '/app/director/reports': typeof AppDirectorReportsRoute
  '/app/swimmer/history': typeof AppSwimmerHistoryRoute
  '/app/swimmer/profile': typeof AppSwimmerProfileRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/coach/': typeof AppCoachIndexRoute
  '/app/director/': typeof AppDirectorIndexRoute
  '/app/swimmer/': typeof AppSwimmerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/terms': typeof TermsRoute
  '/app/admin/invitations': typeof AppAdminInvitationsRoute
  '/app/admin/pending': typeof AppAdminPendingRoute
  '/app/admin/preview': typeof AppAdminPreviewRoute
  '/app/admin/register-trainer': typeof AppAdminRegisterTrainerRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/coach/invitations': typeof AppCoachInvitationsRoute
  '/app/coach/swimmers': typeof AppCoachSwimmersRoute
  '/app/coach/wellness': typeof AppCoachWellnessRoute
  '/app/director/groups': typeof AppDirectorGroupsRoute
  '/app/director/invitations': typeof AppDirectorInvitationsRoute
  '/app/director/reports': typeof AppDirectorReportsRoute
  '/app/swimmer/history': typeof AppSwimmerHistoryRoute
  '/app/swimmer/profile': typeof AppSwimmerProfileRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/coach': typeof AppCoachIndexRoute
  '/app/director': typeof AppDirectorIndexRoute
  '/app/swimmer': typeof AppSwimmerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/coach': typeof AppCoachRouteWithChildren
  '/app/director': typeof AppDirectorRouteWithChildren
  '/app/swimmer': typeof AppSwimmerRouteWithChildren
  '/app/admin/invitations': typeof AppAdminInvitationsRoute
  '/app/admin/pending': typeof AppAdminPendingRoute
  '/app/admin/preview': typeof AppAdminPreviewRoute
  '/app/admin/register-trainer': typeof AppAdminRegisterTrainerRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/coach/invitations': typeof AppCoachInvitationsRoute
  '/app/coach/swimmers': typeof AppCoachSwimmersRoute
  '/app/coach/wellness': typeof AppCoachWellnessRoute
  '/app/director/groups': typeof AppDirectorGroupsRoute
  '/app/director/invitations': typeof AppDirectorInvitationsRoute
  '/app/director/reports': typeof AppDirectorReportsRoute
  '/app/swimmer/history': typeof AppSwimmerHistoryRoute
  '/app/swimmer/profile': typeof AppSwimmerProfileRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/coach/': typeof AppCoachIndexRoute
  '/app/director/': typeof AppDirectorIndexRoute
  '/app/swimmer/': typeof AppSwimmerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/roles'
    | '/terms'
    | '/app/admin'
    | '/app/coach'
    | '/app/director'
    | '/app/swimmer'
    | '/app/admin/invitations'
    | '/app/admin/pending'
    | '/app/admin/preview'
    | '/app/admin/register-trainer'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/coach/invitations'
    | '/app/coach/swimmers'
    | '/app/coach/wellness'
    | '/app/director/groups'
    | '/app/director/invitations'
    | '/app/director/reports'
    | '/app/swimmer/history'
    | '/app/swimmer/profile'
    | '/app/admin/'
    | '/app/coach/'
    | '/app/director/'
    | '/app/swimmer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/roles'
    | '/terms'
    | '/app/admin/invitations'
    | '/app/admin/pending'
    | '/app/admin/preview'
    | '/app/admin/register-trainer'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/coach/invitations'
    | '/app/coach/swimmers'
    | '/app/coach/wellness'
    | '/app/director/groups'
    | '/app/director/invitations'
    | '/app/director/reports'
    | '/app/swimmer/history'
    | '/app/swimmer/profile'
    | '/app/admin'
    | '/app/coach'
    | '/app/director'
    | '/app/swimmer'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/roles'
    | '/terms'
    | '/app/admin'
    | '/app/coach'
    | '/app/director'
    | '/app/swimmer'
    | '/app/admin/invitations'
    | '/app/admin/pending'
    | '/app/admin/preview'
    | '/app/admin/register-trainer'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/coach/invitations'
    | '/app/coach/swimmers'
    | '/app/coach/wellness'
    | '/app/director/groups'
    | '/app/director/invitations'
    | '/app/director/reports'
    | '/app/swimmer/history'
    | '/app/swimmer/profile'
    | '/app/admin/'
    | '/app/coach/'
    | '/app/director/'
    | '/app/swimmer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  TermsRoute: typeof TermsRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCoachRoute: typeof AppCoachRouteWithChildren
  AppDirectorRoute: typeof AppDirectorRouteWithChildren
  AppSwimmerRoute: typeof AppSwimmerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/swimmer': {
      id: '/app/swimmer'
      path: '/app/swimmer'
      fullPath: '/app/swimmer'
      preLoaderRoute: typeof AppSwimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/director': {
      id: '/app/director'
      path: '/app/director'
      fullPath: '/app/director'
      preLoaderRoute: typeof AppDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/app/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/swimmer/': {
      id: '/app/swimmer/'
      path: '/'
      fullPath: '/app/swimmer/'
      preLoaderRoute: typeof AppSwimmerIndexRouteImport
      parentRoute: typeof AppSwimmerRoute
    }
    '/app/director/': {
      id: '/app/director/'
      path: '/'
      fullPath: '/app/director/'
      preLoaderRoute: typeof AppDirectorIndexRouteImport
      parentRoute: typeof AppDirectorRoute
    }
    '/app/coach/': {
      id: '/app/coach/'
      path: '/'
      fullPath: '/app/coach/'
      preLoaderRoute: typeof AppCoachIndexRouteImport
      parentRoute: typeof AppCoachRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/swimmer/profile': {
      id: '/app/swimmer/profile'
      path: '/profile'
      fullPath: '/app/swimmer/profile'
      preLoaderRoute: typeof AppSwimmerProfileRouteImport
      parentRoute: typeof AppSwimmerRoute
    }
    '/app/swimmer/history': {
      id: '/app/swimmer/history'
      path: '/history'
      fullPath: '/app/swimmer/history'
      preLoaderRoute: typeof AppSwimmerHistoryRouteImport
      parentRoute: typeof AppSwimmerRoute
    }
    '/app/director/reports': {
      id: '/app/director/reports'
      path: '/reports'
      fullPath: '/app/director/reports'
      preLoaderRoute: typeof AppDirectorReportsRouteImport
      parentRoute: typeof AppDirectorRoute
    }
    '/app/director/invitations': {
      id: '/app/director/invitations'
      path: '/invitations'
      fullPath: '/app/director/invitations'
      preLoaderRoute: typeof AppDirectorInvitationsRouteImport
      parentRoute: typeof AppDirectorRoute
    }
    '/app/director/groups': {
      id: '/app/director/groups'
      path: '/groups'
      fullPath: '/app/director/groups'
      preLoaderRoute: typeof AppDirectorGroupsRouteImport
      parentRoute: typeof AppDirectorRoute
    }
    '/app/coach/wellness': {
      id: '/app/coach/wellness'
      path: '/wellness'
      fullPath: '/app/coach/wellness'
      preLoaderRoute: typeof AppCoachWellnessRouteImport
      parentRoute: typeof AppCoachRoute
    }
    '/app/coach/swimmers': {
      id: '/app/coach/swimmers'
      path: '/swimmers'
      fullPath: '/app/coach/swimmers'
      preLoaderRoute: typeof AppCoachSwimmersRouteImport
      parentRoute: typeof AppCoachRoute
    }
    '/app/coach/invitations': {
      id: '/app/coach/invitations'
      path: '/invitations'
      fullPath: '/app/coach/invitations'
      preLoaderRoute: typeof AppCoachInvitationsRouteImport
      parentRoute: typeof AppCoachRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/register-trainer': {
      id: '/app/admin/register-trainer'
      path: '/register-trainer'
      fullPath: '/app/admin/register-trainer'
      preLoaderRoute: typeof AppAdminRegisterTrainerRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/preview': {
      id: '/app/admin/preview'
      path: '/preview'
      fullPath: '/app/admin/preview'
      preLoaderRoute: typeof AppAdminPreviewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/pending': {
      id: '/app/admin/pending'
      path: '/pending'
      fullPath: '/app/admin/pending'
      preLoaderRoute: typeof AppAdminPendingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/invitations': {
      id: '/app/admin/invitations'
      path: '/invitations'
      fullPath: '/app/admin/invitations'
      preLoaderRoute: typeof AppAdminInvitationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminInvitationsRoute: typeof AppAdminInvitationsRoute
  AppAdminPendingRoute: typeof AppAdminPendingRoute
  AppAdminPreviewRoute: typeof AppAdminPreviewRoute
  AppAdminRegisterTrainerRoute: typeof AppAdminRegisterTrainerRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminInvitationsRoute: AppAdminInvitationsRoute,
  AppAdminPendingRoute: AppAdminPendingRoute,
  AppAdminPreviewRoute: AppAdminPreviewRoute,
  AppAdminRegisterTrainerRoute: AppAdminRegisterTrainerRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppCoachRouteChildren {
  AppCoachInvitationsRoute: typeof AppCoachInvitationsRoute
  AppCoachSwimmersRoute: typeof AppCoachSwimmersRoute
  AppCoachWellnessRoute: typeof AppCoachWellnessRoute
  AppCoachIndexRoute: typeof AppCoachIndexRoute
}

const AppCoachRouteChildren: AppCoachRouteChildren = {
  AppCoachInvitationsRoute: AppCoachInvitationsRoute,
  AppCoachSwimmersRoute: AppCoachSwimmersRoute,
  AppCoachWellnessRoute: AppCoachWellnessRoute,
  AppCoachIndexRoute: AppCoachIndexRoute,
}

const AppCoachRouteWithChildren = AppCoachRoute._addFileChildren(
  AppCoachRouteChildren,
)

interface AppDirectorRouteChildren {
  AppDirectorGroupsRoute: typeof AppDirectorGroupsRoute
  AppDirectorInvitationsRoute: typeof AppDirectorInvitationsRoute
  AppDirectorReportsRoute: typeof AppDirectorReportsRoute
  AppDirectorIndexRoute: typeof AppDirectorIndexRoute
}

const AppDirectorRouteChildren: AppDirectorRouteChildren = {
  AppDirectorGroupsRoute: AppDirectorGroupsRoute,
  AppDirectorInvitationsRoute: AppDirectorInvitationsRoute,
  AppDirectorReportsRoute: AppDirectorReportsRoute,
  AppDirectorIndexRoute: AppDirectorIndexRoute,
}

const AppDirectorRouteWithChildren = AppDirectorRoute._addFileChildren(
  AppDirectorRouteChildren,
)

interface AppSwimmerRouteChildren {
  AppSwimmerHistoryRoute: typeof AppSwimmerHistoryRoute
  AppSwimmerProfileRoute: typeof AppSwimmerProfileRoute
  AppSwimmerIndexRoute: typeof AppSwimmerIndexRoute
}

const AppSwimmerRouteChildren: AppSwimmerRouteChildren = {
  AppSwimmerHistoryRoute: AppSwimmerHistoryRoute,
  AppSwimmerProfileRoute: AppSwimmerProfileRoute,
  AppSwimmerIndexRoute: AppSwimmerIndexRoute,
}

const AppSwimmerRouteWithChildren = AppSwimmerRoute._addFileChildren(
  AppSwimmerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  TermsRoute: TermsRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCoachRoute: AppCoachRouteWithChildren,
  AppDirectorRoute: AppDirectorRouteWithChildren,
  AppSwimmerRoute: AppSwimmerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
